# Generated by Django 3.0.7 on 2020-06-19 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reply_to', models.EmailField(blank=True, help_text="Taken from html form name='_replyTo' field.", max_length=128, null=True)),
                ('from_name', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=90)),
                ('to', models.EmailField(max_length=128)),
                ('cc', models.TextField(blank=True, help_text='Separate by commas.', null=True)),
                ('bcc', models.TextField(blank=True, help_text='Separate by commas.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('re_captcha', models.CharField(blank=True, help_text='Secret Key', max_length=40, null=True)),
            ],
        ),
    ]
